// <auto-generated />
namespace TH.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SomeChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SomeChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201405130635203_SomeChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
