// <auto-generated />
namespace TH.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class 修Ta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(修Ta));
        
        string IMigrationMetadata.Id
        {
            get { return "201402220911328_修Ta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
